### ISSUE TITLE
有歌词显示么。

### ISSUE THREAD

**Issue by lwjcjmx123** [lavyun/vue-demo-kugou#1]
另外提个建议。可以用cordova或者其他hybrid方法把这个打包成app
哈哈，看了你的个人网站，你是在用MUI是么。这个有打包过么

**Comment by lavyun** [comment]
谢谢建议啊，mui只能说用过，没有过深的研究。这个并没有打包过，mui有它自己一套webview的东西，如果单纯的打包套个壳感觉没有什么意义。歌词显示、进度条我会考虑慢慢加上的，写这个demo的想法就是对学习vue的一个总结，顺便发出来分享分享 O.O
