### ISSUE TITLE
有相关的酷狗的api吗？

### ISSUE THREAD

**Issue by liuxsen** [lavyun/vue-demo-kugou#2]
**有相关的酷狗的api吗？**

**Comment by lavyun** [comment]
我所知道的一个:根据歌曲hash码得到歌曲信详细信息的api。api在demo代码中都能看到

**Comment by xianshenglu** [comment]
这个能看出来，问题是，你是怎么得到 排行，新歌，歌单的列表信息的呢？
http://localhost:8080/proxy/?json=true
http://localhost:8080/proxy/rank/list&json=true
http://localhost:8080/proxy/plist/index&json=true
类似于这些你是怎么得到的呢？

**Comment by xianshenglu** [comment]
这三个难道是定死的？
