### ISSUE TITLE
朋友，npm run dev 后浏览器报错

### ISSUE THREAD

**Issue by nailao** [lavyun/vue-demo-kugou#3]
vue.js?3de6:523[Vue warn]: Error when rendering component <mt-navbar>: warn @ vue.js?3de6:523Vue._render @ vue.js?3de6:2961(anonymous function) @ vue.js?3de6:2191get @ vue.js?3de6:1656Watcher @ vue.js?3de6:1648Vue._mount @ vue.js?3de6:2190Vue$3.$mount @ vue.js?3de6:5978Vue$3.$mount @ vue.js?3de6:8301init @ vue.js?3de6:2502createComponent @ vue.js?3de6:4052createElm @ vue.js?3de6:3995createChildren @ vue.js?3de6:4103createElm @ vue.js?3de6:4028patch @ vue.js?3de6:4446Vue._update @ vue.js?3de6:2217(anonymous function) @ vue.js?3de6:2191get @ vue.js?3de6:1656Watcher @ vue.js?3de6:1648Vue._mount @ vue.js?3de6:2190Vue$3.$mount @ vue.js?3de6:5978Vue$3.$mount @ vue.js?3de6:8301init @ vue.js?3de6:2502createComponent @ vue.js?3de6:4052createElm @ vue.js?3de6:3995createChildren @ vue.js?3de6:4103createElm @ vue.js?3de6:4028patch @ vue.js?3de6:4446Vue._update @ vue.js?3de6:2217(anonymous function) @ vue.js?3de6:2191get @ vue.js?3de6:1656Watcher @ vue.js?3de6:1648Vue._mount @ vue.js?3de6:2190Vue$3.$mount @ vue.js?3de6:5978Vue$3.$mount @ vue.js?3de6:8301init @ vue.js?3de6:2502createComponent @ vue.js?3de6:4052createElm @ vue.js?3de6:3995createChildren @ vue.js?3de6:4103createElm @ vue.js?3de6:4028patch @ vue.js?3de6:4446Vue._update @ vue.js?3de6:2217(anonymous function) @ vue.js?3de6:2191get @ vue.js?3de6:1656Watcher @ vue.js?3de6:1648Vue._mount @ vue.js?3de6:2190Vue$3.$mount @ vue.js?3de6:5978Vue$3.$mount @ vue.js?3de6:8301init @ vue.js?3de6:2502createComponent @ vue.js?3de6:4052createElm @ vue.js?3de6:3995patch @ vue.js?3de6:4483Vue._update @ vue.js?3de6:2217(anonymous function) @ vue.js?3de6:2191get @ vue.js?3de6:1656Watcher @ vue.js?3de6:1648Vue._mount @ vue.js?3de6:2190Vue$3.$mount @ vue.js?3de6:5978Vue$3.$mount @ vue.js?3de6:8301initRender @ vue.js?3de6:2918Vue._init @ vue.js?3de6:3296Vue$3 @ vue.js?3de6:3343(anonymous function) @ main.js?3479:14(anonymous function) @ app.js:1098__webpack_require__ @ app.js:556fn @ app.js:87(anonymous function) @ app.js:587__webpack_require__ @ app.js:556(anonymous function) @ app.js:579(anonymous function) @ app.js:582
vue.js?3de6:2963Uncaught ReferenceError: _h is not defined

**Comment by joden2014** [comment]
![image](https://cloud.githubusercontent.com/assets/7391611/21177005/3c04bcca-c224-11e6-8d2f-85cfc0e9fe0b.png)
