### ISSUE TITLE
代码疑问：3点

### ISSUE THREAD

**Issue by wwb568109135** [lavyun/vue-demo-kugou#5]
（1）beforeRouteEnter，beforeRouteLeave  在官方vuejs2 文档api都没有出现这个，作者用了，合适吗？

    //通过路由的before钩子解除router-view缓存限制
    beforeRouteEnter (to, from, next) {
      next(vm => {
        vm.$store.commit('showHead',true);
        vm.get();
        window.onscroll=()=>{
          vm.opacity=window.pageYOffset/250;
          vm.$store.commit('setHeadStyle',{background:'rgba(43,162,251,'+vm.opacity+')'})
        }
      })
    },
    beforeRouteLeave(to,from,next){
      this.$store.commit('showHead',false);
      window.onscroll=null;
      next()
    },

（2）miut－ui 的不是开始main.js 入口那里 全部导入进去了吗 ？
但是作者在用到该ui的地方 用重现导入的一边了，譬如：vue-demo-kugou/src/views/plist.vue
import { Cell,Indicator } from 'mint-ui'

（3）this.store.dispatch 是调用actions，this.store.commit是mutations，对吗?

**Comment by lavyun** [comment]
1.我这样写可以解决keep-alive对所有路由的缓存问题，好像vue最近的更新有部分缓存的机制。官方文档是有限的，很多技巧还需要在实例编码中发掘。
2.仔细看了下文档，我这样写确实有问题。
3.和你说的一样
