### ISSUE TITLE
[error]Cannot resolve module 'babel-runtime/helpers/extends' 

### ISSUE THREAD

**Issue by liary** [lavyun/vue-demo-kugou#6]
error showed when I execute `npm run dev`:

`ERROR in ./src/store/index.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in /Us
ers/[mosaic]/Downloads/vue-demo-kugou-master/src/store
 @ ./src/store/index.js 7:16-56`
finally I add in `babel-runtime`：
  "dependencies": {
    "babel-runtime": "^6.20.0",
    "json-loader": "^0.5.4",
    "vue": "^2.0.1"
  }
it works^ . ^

**Comment by lavyun** [comment]
you should do npm install first

**Comment by lavyun** [comment]
Thanks your feedback.
I tried it on again, there is no problem.
It may be some errors occurred at the time of NPM INSTALL, so babel -  runtime has not installed.
My English was not good,please forgive me.

**Comment by lavyun** [comment]
I have a question:两个中国人为什么要用英文对话。。。。

**Comment by liary** [comment]
我竟无言以对😂
